export const TOTAL_MACHINE_CASH_ADMIN = 'TOTAL_MACHINE_CASH_ADMIN';
export const INC_QUANTITY_ITEM_ADMIN = 'INC_QUANTITY_ITEM_ADMIN';
export const DEC_QUANTITY_ITEM_ADMIN = 'DEC_QUANTITY_ITEM_ADMIN';
export const INC_PRICE_ITEM_ADMIN = 'INC_PRICE_ITEM_ADMIN';
export const DEC_PRICE_ITEM_ADMIN = 'DEC_PRICE_ITEM_ADMIN';
export const TOTAL_ENERGY_CONSUPTION_ADMIN = 'TOTAL_ENERGY_CONSUPTION_ADMIN';
export const RESET = 'RESET';
export const SET_TIMER = 'SET_TIMER';